package com.avarta.integrationlibrary.interfaces;

public interface ApiErrorCode {
    int ORGANIZATION_RECORD_NOT_FOUND = 0;
    int USER_RECORD_NOT_FOUND = 1;
    int USER_NOT_ASSOCIATED_WITH_ORGANIZATION = 2;
    int WORKFLOW_NOT_ASSOCIATED_WITH_ORGANIZATION = 3;
    int WORKFLOW_NOT_FOUND = 4;
    int MISSING_ORGANIZATION_HEADER = 8;
    int ATTEMPT_TO_LAUNCH_SECONDARY_WORKFLOW = 9;
    int USER_ACCOUNT_LOCKED = 10;
    int MESSAGE_BODY_INVALID = 14;
    int USER_NOT_ENROLLED = 18;
    int USER_ALREADY_ENROLLED = 19;
    int NO_DETAILS_FOR_ORG_APPLICATION_EXCEPTION = 20;
}
